[build]
  functions = "netlify/functions"
  publish = "."

[functions]
  included_files = ["netlify/functions/files/**"]

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
